### ISSUE TITLE
The service will generate a pageUrls on its own domain

### ISSUE THREAD

**Issue by poi33** [enonic/app-metafields#108]
The service for the metafields app will have all of its pageUrls based on its own domain. 
As the service was created for headless use of the app it will most likely be hosted on another domain. 

Example of problem:
mydomain.com/ host the server while newsite.com/ host the frontend

When getting the service data it will contain mydomain.com/ urls. 
It would be better if the service did not add any domain to the paths and let the headless side prepend the domains to the data.

**Comment by ComLock** [comment]
There is no longer any service
