### ISSUE TITLE
Add option for turning off all search engine tracking

### ISSUE THREAD

**Issue by selbekk** [enonic/app-metafields#12]
We just launched an open beta of our new website, and we don't want it to be tracked by search engines.

We want to turn off the searchability of the site globally. Another use case is turning off searchability from a page-to-page basis. 

Is this something we could implement?

**Comment by sigdestad** [comment]
Maybe use robots.txt?

Vennlig hilsen/Best regards 

Thomas Sigdestad
CTO & Co-Founder

https://enonic.com - A web operating system for your sites and applications

**Comment by selbekk** [comment]
`robots.txt` is good for developers but bad for web editors.

**Comment by sigdestad** [comment]
I’m just suggesting that you generate one automatically, i.e. based on a setting in the site config for the metafields app.
Use a filter - for 6.5. mappings look promising :-)
‌‌
Vennlig hilsen/Best regards
Enonic AS

Thomas Sigdestad
CTO

https://enonic.com <https://enonic.com/> - A web operating system for your sites and applications

**Comment by selbekk** [comment]
Generating one could definitely be done, but I think setting it via meta tags might be just as good :)
