### ISSUE TITLE
Custom JSON-path feature cannot handle array-typed data, like item-sets

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-metafields#19]
If a content type has data stored inside itemsets, most commonly combinations of caption+image, we can't add a custom json path for it. At least I think. Take a closer look on this and verify.

Investigate how we can make it work. It's a bit tricky since itemsets are wrapped as an array. Perhaps `images[].image`-format is required? That way we detect `[]` and map accordingly. Be aware of forceArray problems too.

Example Content Type that could work:
```
<item-set>
<input type="ImageSelector" name="portrait" />
<input type="ContentSelector" name="linkto"/>
```

**Comment by Slideshow776** [comment]
@alansemenov This error also occurs in content types if you have a field using one of the reserved names that is an array. For example, if you have content type called `article`, containing fields called `image` or `images` (reserved/used name by the app - code found in /lib/common.js of this app) and these fields allow more than 1 item (thus returning arrays instead of strings) it will crash the app.

**Comment by Slideshow776** [comment]
```
<item-set name="images">
            <label>Bildegalleri</label>
            <immutable>false</immutable>
            <occurrences maximum="0" minimum="0"/>
            <items>
                <input name="image" type="ImageSelector">
                    <label>Bilde</label>
                    <custom-text>image</custom-text>
                    <immutable>false</immutable>
                    <indexed>false</indexed>
                    <maximize>true</maximize>
                    <occurrences maximum="1" minimum="0"/>
                    <config/>
                </input>
                <input name="imagecaption" type="TextLine">
                    <label>Bildetekst</label>
                    <custom-text>imagecaption</custom-text>
                    <immutable>false</immutable>
                    <indexed>false</indexed>
                    <maximize>true</maximize>
                  <occurrences maximum="1" minimum="0"/>
                    <config/>
                </input>
            </items>
        </item-set>
```
