### ISSUE TITLE
Priority field for use in sitemap.xml

### ISSUE THREAD

**Issue by prebenborch** [enonic/app-metafields#21]
It would be nice to have a priority field (sitemap.xml specific field) along with "hide from search engines" in the metadata section - for sitemap.xml service we have made. I would guess this is something so generic that everybody can make use of it.

**Comment by Bellfalasch** [comment]
Only challenge is that we also have a sitemap.xml app, and this kind of session feels like it belongs more there than here.

**Comment by Bellfalasch** [comment]
The last few years few even use the `<priority>` field. So we will not implement this. Use `<lastmod>` to signal changed content.
One of many links talking about this: https://www.seroundtable.com/google-priority-change-frequency-xml-sitemap-20273.html
Google is open with this not being used.
