### ISSUE TITLE
Changing the label for hide from search engine text in seo meta app.

### ISSUE THREAD

**Issue by singhalv12** [enonic/app-metafields#30]
We want to change the text for Seo Meta data label from  `Hide from search engines?` to `Hide from external search engines?` . Will it be possible to change in upcoming release for Enonic ?

![image](https://user-images.githubusercontent.com/17567370/30906396-0b7ae9b8-a378-11e7-8ea5-03d8fa4ebfee.png)

**Comment by Bellfalasch** [comment]
This will ship in 1.4.0
