### ISSUE TITLE
Meta fields are not visible with new implementation of x-data

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-metafields#34]
@sgauruseu commented on [Mon Oct 01 2018](https://github.com/enonic/xp/issues/6632)

This is not  XP-bug, this is issue in `SEO metadata ` application
1. Install the  https://market.enonic.com/vendors/enonic/com.enonic.app.metafields
2. Open new site wizard , select the application

Bug:  Meta fields are not visible

![image](https://user-images.githubusercontent.com/3728712/46294794-44d3c000-c59f-11e8-92f2-4519d67ac2f1.png)

**Comment by Bellfalasch** [comment]
Not possible for apps to control this behaviour.
