### ISSUE TITLE
Crashing on array of images

### ISSUE THREAD

**Issue by viggo** [enonic/app-metafields#40]
When a content has an array of images SEO Metafields app gives a 500 error:
<img width="803" alt="screen shot 2019-01-28 at 15 34 25" src="https://user-images.githubusercontent.com/441696/51842901-3c538200-2312-11e9-986d-2e460b83eaf9.png">

https://github.com/enonic/app-metafields/blob/master/src/main/resources/lib/common.js#L98

Content type image definition:
```
<input type="ImageSelector" name="image">
    <label>Featured image</label>
    <occurrences minimum="4" maximum="4"/>
    <config>
        <allowPath>${site}</allowPath>
    </config>
</input>
```

**Comment by alansemenov** [comment]
Solved by renaming the input to ``images``
