### ISSUE TITLE
remove/hide canonical on certains vhosts

### ISSUE THREAD

**Issue by diegopasten** [enonic/app-metafields#42]
Currently the metafields app adds canonical to all content that is managed by XP. 

So if a user has two or more sites/vhosts on the same server, where one is intended for development and another for production they will all be crawled by search engines as canonical.

What would be nice is to exclude tagging content as canonical by enonic xp vhost.
blog.mydomain.com
blog.mytestdomain.com <- exclude this.

**Comment by diegopasten** [comment]
... or a different solution that fixes the same issue is of course also okay :)

**Comment by poi33** [comment]
@diegopasten does the robots.txt not stop crawling of sites? 
So that you can exclude the entire page if you want?

**Comment by diegopasten** [comment]
@poi33 I guess that you are right, and it was probably how it was "solved". But I can not really remember what happened with this issue.

**Comment by poi33** [comment]
I'm close this since robots.txt should stop crawling of sites that are not linking to eachother.
