### ISSUE TITLE
Update metafields about

### ISSUE THREAD

**Issue by poi33** [enonic/app-metafields#71]
On this repo the about says its an xp6 app. 

We upgraded it a long time ago.

**Comment by alansemenov** [comment]
Can you point/link to the place where it says that? Or, even better, just fix it. These small text fixes don't even need an issue.

**Comment by poi33** [comment]
![image](https://user-images.githubusercontent.com/3340349/135419116-81dc942d-735d-455f-8f17-071bceff381b.png)
I don't have repo access, so i can not change it. 
That is the main reason i created an issue
