### ISSUE TITLE
Include Nynorsk in list of possible languages

### ISSUE THREAD

**Issue by jonaslepsoy** [enonic/app-metafields#78]
Problem:
When choosing "Nynorsk" as the language for a content item, the `getLang` function returns `en_US`. 

To reproduce:

1. Change a content's language to "Nynorsk", either `norsk (Noreg, nynorsk) (nn-NO-NY)`, `nynorsk (nn)` or `nynorsk (Noreg) (nn-NO)`.
2. Open the content in preview mode and observe that `<meta property="og:locale" content="en_US">` is present in the resulting HTML.

Expected behaviour:
The `getLang` functions returns `nn_NO` for content with "Nynorsk" as the chosen language.

https://github.com/enonic/app-metafields/blob/c674fb3866f9724bb4ae40c5e90812d18cc99cb1/src/main/resources/lib/common.js#L30-L41

**Comment by poi33** [comment]
@jonaslepsoy this should be fixed in master now #80. Will be included in the next release. (Should be as soon as i have time to build it)
