### ISSUE TITLE
Wrong image shared in social media

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-metafields#93]
This post: https://enonic.com/blog/benefits-next-gen-headless-cms

When sharing on e.g. LinkedIn, the wrong image is fetched as a preview.

1) I went back to the post in Content Studio and set the right image via the SEO Meta Fields app
2) I went to LinkedIn Post Inspector to scrape the new info

But the issue still persists. Is this a Content Studio error, or something related to Enonic.com?

The OG:image tag on the rendered page says the following: /site/company-web/master/enonic-homepage/blog/benefits-next-gen-headless-cms/_/error/400?message=URI+out+of+scope

There is something wrong here.

**Comment by poi33** [comment]
Moved to to metafields app: https://github.com/enonic/app-metafields/issues/93

**Comment by vot-enonic** [comment]
This error could be due to the XP and Content Studio update from yesterday @alansemenov

**Comment by alansemenov** [comment]
Will be fixed in https://github.com/enonic/xp/issues/9645 (XP 7.10.2)
